"""
Starter scholarship dataset (26 real, well-known global scholarships with
official links). This is a seed, not the ceiling — the admin API is how
you grow this toward your full catalogue.
"""

SEED_SCHOLARSHIPS = [
    dict(name="Chevening Scholarships", provider="UK Government", country="United Kingdom",
         level="Master's", field="All fields", funding="Fully-funded", deadline_window="Aug–Nov",
         official_link="https://www.chevening.org/", tags=["Leadership", "Government"],
         blurb="UK government award for future leaders, fully funds a one-year master's plus a living stipend and travel."),
    dict(name="Fulbright Foreign Student Program", provider="U.S. Department of State", country="United States",
         level="Master's / PhD", field="All fields", funding="Fully-funded", deadline_window="Feb–May",
         official_link="https://foreign.fulbrightonline.org/", tags=["Exchange", "All Fields"],
         blurb="Flagship US government exchange program; deadlines are set by the Fulbright Commission or U.S. Embassy in each country."),
    dict(name="DAAD EPOS Scholarships", provider="German Academic Exchange Service", country="Germany",
         level="Master's / PhD", field="Development-related fields", funding="Fully-funded", deadline_window="Jul–Oct",
         official_link="https://www.daad.de/en/", tags=["Development", "Germany"],
         blurb="Germany's academic exchange service funds postgraduate study for students from developing countries in EPOS-listed programmes."),
    dict(name="Erasmus Mundus Joint Master Degrees", provider="European Commission", country="Europe (multi-country)",
         level="Master's", field="Varies by consortium", funding="Fully-funded", deadline_window="Nov–Jan",
         official_link="https://education.ec.europa.eu/", tags=["Europe", "Joint Degree"],
         blurb="Study at two or more European universities on one joint degree; each consortium sets its own intake and deadline."),
    dict(name="Commonwealth Scholarships", provider="UK Government (CSC)", country="United Kingdom",
         level="Master's / PhD", field="Development-related fields", funding="Fully-funded", deadline_window="Oct–Dec",
         official_link="https://cscuk.fcdo.gov.uk/", tags=["Commonwealth", "Development"],
         blurb="For citizens of Commonwealth countries; prioritises subjects linked to development."),
    dict(name="Gates Cambridge Scholarship", provider="Gates Foundation & University of Cambridge", country="United Kingdom",
         level="Master's / PhD", field="All fields", funding="Fully-funded", deadline_window="Oct–Dec",
         official_link="https://www.gatescambridge.org/", tags=["Cambridge", "All Fields"],
         blurb="Funds outstanding applicants from outside the UK to study any full-time postgraduate course at the University of Cambridge."),
    dict(name="Rhodes Scholarship", provider="Rhodes Trust, Oxford", country="United Kingdom",
         level="Master's / DPhil", field="All fields", funding="Fully-funded", deadline_window="Jul–Oct",
         official_link="https://www.rhodeshouse.ox.ac.uk/", tags=["Oxford", "Leadership"],
         blurb="One of the oldest international scholarships, funding study at the University of Oxford."),
    dict(name="Australia Awards Scholarships", provider="Australian Government", country="Australia",
         level="Master's / PhD", field="Development priority fields", funding="Fully-funded", deadline_window="Feb–Apr",
         official_link="https://www.australiaawards.gov.au/", tags=["Australia", "Development"],
         blurb="Australian government scholarships supporting long-term development in partner countries."),
    dict(name="MEXT Scholarship", provider="Japanese Ministry of Education", country="Japan",
         level="Undergraduate / Master's / PhD", field="All fields", funding="Fully-funded", deadline_window="Apr–Jun",
         official_link="https://www.studyinjapan.go.jp/", tags=["Japan", "All Levels"],
         blurb="Japan's Ministry of Education scholarship; most applicants apply through their local Japanese embassy."),
    dict(name="Türkiye Bursları", provider="Turkish Government", country="Turkey",
         level="Undergraduate / Master's / PhD", field="All fields", funding="Fully-funded", deadline_window="Jan–Feb",
         official_link="https://www.turkiyeburslari.gov.tr/", tags=["Turkey", "All Levels"],
         blurb="Turkish government scholarship covering tuition, housing, healthcare, a monthly stipend and a Turkish-language course."),
    dict(name="Vanier Canada Graduate Scholarships", provider="Government of Canada", country="Canada",
         level="PhD", field="All fields", funding="Fully-funded", deadline_window="Sep–Nov",
         official_link="https://vanier.gc.ca/", tags=["Canada", "PhD"],
         blurb="Canada's premier doctoral scholarship for research excellence, leadership and academic achievement."),
    dict(name="Knight-Hennessy Scholars", provider="Stanford University", country="United States",
         level="Any graduate degree", field="All fields", funding="Fully-funded", deadline_window="Sep–Oct",
         official_link="https://knight-hennessy.stanford.edu/", tags=["Stanford", "Leadership"],
         blurb="Funds graduate study in any field at Stanford, with a focus on developing multidisciplinary leaders."),
    dict(name="Schwarzman Scholars", provider="Schwarzman Scholars, Tsinghua University", country="China",
         level="Master's", field="Public policy, economics, international relations", funding="Fully-funded", deadline_window="Sep",
         official_link="https://www.schwarzmanscholars.org/", tags=["China", "Policy"],
         blurb="One-year master's in global affairs at Tsinghua University, Beijing, designed to build understanding of China."),
    dict(name="Joint Japan/World Bank Graduate Scholarship", provider="World Bank Group", country="Study worldwide",
         level="Master's", field="Development-related fields", funding="Fully-funded", deadline_window="Mar–Apr",
         official_link="https://www.worldbank.org/en/programs/scholarships", tags=["Development", "Global"],
         blurb="For professionals from World Bank member developing countries pursuing development-related master's degrees."),
    dict(name="Swiss Government Excellence Scholarships", provider="Swiss Government", country="Switzerland",
         level="PhD / Postdoc", field="All fields", funding="Fully-funded", deadline_window="Sep",
         official_link="https://www.sbfi.admin.ch/", tags=["Switzerland", "Research"],
         blurb="Awarded to promising young researchers and artists, applied for through the relevant national agency."),
    dict(name="Holland Scholarship", provider="Dutch Government & Universities", country="Netherlands",
         level="Undergraduate / Master's", field="Varies", funding="Partial", deadline_window="Jan–Feb",
         official_link="https://www.studyinholland.nl/", tags=["Netherlands", "Partial"],
         blurb="A one-time grant from the Dutch government and participating universities for non-EEA students."),
    dict(name="New Zealand Scholarships", provider="New Zealand Government", country="New Zealand",
         level="Master's / PhD", field="Development priority fields", funding="Fully-funded", deadline_window="Feb",
         official_link="https://www.mfat.govt.nz/", tags=["New Zealand", "Pacific"],
         blurb="Manaaki New Zealand Scholarships support students from Pacific and other partner countries."),
    dict(name="Killam Fellowships", provider="Killam Trusts", country="Canada / United States",
         level="Undergraduate exchange", field="All fields", funding="Fully-funded", deadline_window="Nov",
         official_link="https://www.killamfellowships.com/", tags=["Canada", "Exchange"],
         blurb="A year-long exchange between Canadian and American universities for undergraduates."),
    dict(name="Global Korea Scholarship (GKS)", provider="Korean Government (NIIED)", country="South Korea",
         level="Undergraduate / Master's / PhD", field="All fields", funding="Fully-funded", deadline_window="Feb & Sep",
         official_link="https://www.studyinkorea.go.kr/", tags=["Korea", "All Levels"],
         blurb="South Korea's national scholarship, applied for via Korean embassies or directly through host universities."),
    dict(name="ADB-Japan Scholarship Program", provider="Asian Development Bank", country="Study at ADB partner universities in Asia",
         level="Master's", field="Development-related fields", funding="Fully-funded", deadline_window="Varies",
         official_link="https://www.adb.org/", tags=["Asia", "Development"],
         blurb="Funded by the Asian Development Bank for students from its developing member countries."),
    dict(name="Chinese Government Scholarship (CSC)", provider="China Scholarship Council", country="China",
         level="Undergraduate / Master's / PhD", field="All fields", funding="Fully-funded", deadline_window="Jan–Apr",
         official_link="https://www.campuschina.org/", tags=["China", "All Levels"],
         blurb="Administered by the China Scholarship Council, either through embassies or directly through universities."),
    dict(name="Rotary Peace Fellowship", provider="Rotary Foundation", country="Global (Rotary Peace Centers)",
         level="Master's / Certificate", field="Peace and development studies", funding="Fully-funded", deadline_window="May",
         official_link="https://www.rotary.org/en/our-programs/peace-fellowships", tags=["Peace Studies", "Global"],
         blurb="Trains leaders in peace and conflict resolution at Rotary Peace Centers around the world."),
    dict(name="Mastercard Foundation Scholars Program", provider="Mastercard Foundation", country="Africa-focused",
         level="Undergraduate / Master's", field="All fields", funding="Fully-funded", deadline_window="Varies",
         official_link="https://mastercardfdn.org/en/", tags=["Africa", "Undergraduate"],
         blurb="Supports academically talented young people, primarily from Africa, facing economic barriers to education."),
    dict(name="Beit Trust Scholarships", provider="Beit Trust", country="Zambia, Zimbabwe, Malawi",
         level="Undergraduate / Master's", field="All fields", funding="Fully-funded", deadline_window="Aug–Oct",
         official_link="https://www.beittrust.org.uk/", tags=["Southern Africa", "All Levels"],
         blurb="Supports postgraduate and some undergraduate study for students from Zambia, Zimbabwe and Malawi."),
    dict(name="Islamic Development Bank Scholarship Programme", provider="Islamic Development Bank", country="IsDB member countries",
         level="Master's / PhD", field="Science and technology priority", funding="Fully-funded", deadline_window="Varies",
         official_link="https://www.isdb.org/", tags=["STEM", "Member Countries"],
         blurb="Merit and need-based scholarships for students from Islamic Development Bank member and Muslim communities in non-member countries."),
    dict(name="Erasmus+ Student Mobility", provider="European Commission", country="Europe",
         level="Exchange semester", field="All fields", funding="Partial grant", deadline_window="Varies",
         official_link="https://education.ec.europa.eu/", tags=["Exchange", "Partial"],
         blurb="A partial grant supporting a semester or year studying at a partner university in Europe."),
]
